openapi: '3.0.2'
info:
  title: OlearingAPI
  version: '1.0'
servers:
  - url: https://oschool.topwork.asia/api
paths:
  /test:
    get:
      responses:
        '200':
          description: OK

    post:
      responses:
        '200':
          description: OK

    patch:
      responses:
        '200':
          description: OK
          


    



  